"""Endpoint registry for FTShare market data."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Endpoint:
    """Metadata for a single FTShare API endpoint."""

    name: str
    path: str | None
    method: str = "GET"
    title: str = ""
    doc_file: str | None = None
    original_api: str = ""
    params: tuple[str, ...] = ()
    path_params: tuple[str, ...] = ()
    max_page_size: int = 200


ENDPOINTS: dict[str, Endpoint] = {
    'abnormal_trading_details': Endpoint(
        name='abnormal_trading_details',
        path='api/v1/market/data/abnormal-trading-details',
        method='GET',
        title='龙虎榜明细',
        doc_file='龙虎榜明细.md',
        original_api='abnormal_trading_details',
        params=('date',),
        path_params=(),
        max_page_size=200,
    ),
    'abnormal_trading_overview': Endpoint(
        name='abnormal_trading_overview',
        path='api/v1/market/data/abnormal-trading-overview',
        method='GET',
        title='龙虎榜总览',
        doc_file='龙虎榜总览.md',
        original_api='abnormal_trading_overview',
        params=('date',),
        path_params=(),
        max_page_size=200,
    ),
    'auction_results': Endpoint(
        name='auction_results',
        path='api/v1/market/data/auction-results',
        method='GET',
        title='集合竞价结果',
        doc_file='集合竞价结果.md',
        original_api='auction_results',
        params=('ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'baidu_financial_calendar': Endpoint(
        name='baidu_financial_calendar',
        path='api/v1/market/data/finance/financial-calendar/baidu',
        method='GET',
        title='百度财经日历',
        doc_file='百度财经日历.md',
        original_api='baidu_financial_calendar',
        params=('start_date', 'end_date', 'category', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'balance': Endpoint(
        name='balance',
        path='api/v1/market/data/finance/balance',
        method='GET',
        title='A股资产负债表',
        doc_file='A股资产负债表.md',
        original_api='balance',
        params=('stock_code', 'year', 'report_type', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'block_trades': Endpoint(
        name='block_trades',
        path='api/v1/market/data/block-trades',
        method='GET',
        title='大宗交易',
        doc_file='大宗交易.md',
        original_api='block_trades',
        params=('date',),
        path_params=(),
        max_page_size=200,
    ),
    'bse_mapping': Endpoint(
        name='bse_mapping',
        path='api/v1/market/data/bse-mapping',
        method='GET',
        title='北交所映射',
        doc_file='北交所映射.md',
        original_api='get_bse_mapping',
        params=('o_code', 'n_code'),
        path_params=(),
        max_page_size=200,
    ),
    'bullion_price': Endpoint(
        name='bullion_price',
        path='api/v1/market/data/bullion/price',
        method='GET',
        title='贵金属价格',
        doc_file='贵金属价格.md',
        original_api='get_bullion_price',
        params=('symbol', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'bullion_support_symbol': Endpoint(
        name='bullion_support_symbol',
        path='api/v1/market/data/bullion/support-symbol',
        method='GET',
        title='贵金属支持标的',
        doc_file='贵金属支持标的.md',
        original_api='get_bullion_support_symbol',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'cashflow': Endpoint(
        name='cashflow',
        path='api/v1/market/data/finance/cashflow',
        method='GET',
        title='A股现金流量表',
        doc_file='A股现金流量表.md',
        original_api='cashflow',
        params=('stock_code', 'year', 'report_type', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'cashflow_stock_code': Endpoint(
        name='cashflow_stock_code',
        path='api/v1/market/data/finance/cashflow-stock-code',
        method='GET',
        title='现金流支持股票代码',
        doc_file='现金流支持股票代码.md',
        original_api='get_cashflow_stock_code',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'cb_base_data': Endpoint(
        name='cb_base_data',
        path='api/v1/market/data/cb/cb-base-data',
        method='GET',
        title='可转债基础数据',
        doc_file='可转债基础数据.md',
        original_api='get_cb_base_data_handler',
        params=('symbol_code',),
        path_params=(),
        max_page_size=200,
    ),
    'cb_lists': Endpoint(
        name='cb_lists',
        path='api/v1/market/data/cb/cb-lists',
        method='GET',
        title='可转债列表',
        doc_file='可转债列表.md',
        original_api='get_cb_lists_handler',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'china_futures_base_data': Endpoint(
        name='china_futures_base_data',
        path='api/v1/market/data/futures/futures-base-data',
        method='GET',
        title='中国期货基础数据',
        doc_file='中国期货基础数据.md',
        original_api='get_china_futures_base_data_handler',
        params=('trade_date', 'symbol'),
        path_params=(),
        max_page_size=200,
    ),
    'china_futures_lists': Endpoint(
        name='china_futures_lists',
        path='api/v1/market/data/futures/futures-lists',
        method='GET',
        title='中国期货列表',
        doc_file='中国期货列表.md',
        original_api='get_china_futures_lists_handler',
        params=('trade_date',),
        path_params=(),
        max_page_size=200,
    ),
    'company_hk': Endpoint(
        name='company_hk',
        path='api/v1/market/data/hk/company-hk',
        method='GET',
        title='港股公司信息',
        doc_file='港股公司信息.md',
        original_api='get_company_hk',
        params=('trade_code',),
        path_params=(),
        max_page_size=200,
    ),
    'company_list': Endpoint(
        name='company_list',
        path='api/v1/market/data/company-list',
        method='GET',
        title='公司列表',
        doc_file='公司列表.md',
        original_api='get_company_list',
        params=('stock_name', 'stock_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_credit_monthly': Endpoint(
        name='consumer_credit_monthly',
        path='api/v1/market/data/economic/china-credit-loans',
        method='GET',
        title='社融信贷',
        doc_file='社融信贷.md',
        original_api='consumer_credit_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_customs_trade_monthly': Endpoint(
        name='consumer_customs_trade_monthly',
        path='api/v1/market/data/economic/china-customs-trade',
        method='GET',
        title='进出口',
        doc_file='进出口.md',
        original_api='consumer_customs_trade_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_fiscal_revenue_monthly': Endpoint(
        name='consumer_fiscal_revenue_monthly',
        path='api/v1/market/data/economic/china-fiscal-revenue',
        method='GET',
        title='财政收入',
        doc_file='财政收入.md',
        original_api='consumer_fiscal_revenue_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_fixed_asset_monthly': Endpoint(
        name='consumer_fixed_asset_monthly',
        path='api/v1/market/data/economic/china-fixed-asset-investment',
        method='GET',
        title='固定资产投资',
        doc_file='固定资产投资.md',
        original_api='consumer_fixed_asset_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_forex_gold_monthly': Endpoint(
        name='consumer_forex_gold_monthly',
        path='api/v1/market/data/economic/china-forex-gold',
        method='GET',
        title='外汇黄金',
        doc_file='外汇黄金.md',
        original_api='consumer_forex_gold_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_gdp_quarterly': Endpoint(
        name='consumer_gdp_quarterly',
        path='api/v1/market/data/economic/china-gdp',
        method='GET',
        title='GDP',
        doc_file='GDP.md',
        original_api='consumer_gdp_quarterly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_industrial_added_value_monthly': Endpoint(
        name='consumer_industrial_added_value_monthly',
        path='api/v1/market/data/economic/china-industrial-added-value',
        method='GET',
        title='工业增加值',
        doc_file='工业增加值.md',
        original_api='consumer_industrial_added_value_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_money_supply_monthly': Endpoint(
        name='consumer_money_supply_monthly',
        path='api/v1/market/data/economic/china-money-supply',
        method='GET',
        title='货币供应',
        doc_file='货币供应.md',
        original_api='consumer_money_supply_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_pmi_monthly': Endpoint(
        name='consumer_pmi_monthly',
        path='api/v1/market/data/economic/china-pmi',
        method='GET',
        title='PMI',
        doc_file='PMI.md',
        original_api='consumer_pmi_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_ppi_monthly': Endpoint(
        name='consumer_ppi_monthly',
        path='api/v1/market/data/economic/china-ppi',
        method='GET',
        title='PPI',
        doc_file='PPI.md',
        original_api='consumer_ppi_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_price_index_monthly': Endpoint(
        name='consumer_price_index_monthly',
        path='api/v1/market/data/economic/china-cpi',
        method='GET',
        title='CPI',
        doc_file='CPI.md',
        original_api='consumer_price_index_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'consumer_retail_sales_monthly': Endpoint(
        name='consumer_retail_sales_monthly',
        path='api/v1/market/data/economic/china-retail-sales',
        method='GET',
        title='社零',
        doc_file='社零.md',
        original_api='consumer_retail_sales_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'earnings_reports_paginated': Endpoint(
        name='earnings_reports_paginated',
        path='api/v1/market/data/finance/stock-performance-express',
        method='GET',
        title='业绩快报',
        doc_file='业绩快报.md',
        original_api='earnings_reports_paginated',
        params=('stock_code', 'year', 'report_type', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'eastmoney_board_constituents': Endpoint(
        name='eastmoney_board_constituents',
        path='api/v1/market/data/eastmoney-board-constituents',
        method='GET',
        title='东方财富板块成份股',
        doc_file='东方财富板块成份股.md',
        original_api='eastmoney_board_constituents',
        params=('board_code',),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_board_daily_kline': Endpoint(
        name='eastmoney_board_daily_kline',
        path='api/v1/market/data/eastmoney-board-daily-ohlc',
        method='GET',
        title='东方财富板块日线OHLC',
        doc_file='东方财富板块日线OHLC.md',
        original_api='eastmoney_board_daily_kline',
        params=('board_code', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_board_latest_kline': Endpoint(
        name='eastmoney_board_latest_kline',
        path='api/v1/market/data/eastmoney-board-latest-ohlc',
        method='GET',
        title='东方财富板块最新OHLC',
        doc_file='东方财富板块最新OHLC.md',
        original_api='eastmoney_board_latest_kline',
        params=('board_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_concept_boards': Endpoint(
        name='eastmoney_concept_boards',
        path='api/v1/market/data/eastmoney-concept-boards',
        method='GET',
        title='东方财富概念板块',
        doc_file='东方财富概念板块.md',
        original_api='eastmoney_concept_boards',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_dapan_flow': Endpoint(
        name='eastmoney_dapan_flow',
        path='api/v1/market/data/eastmoney-dapan-flow',
        method='GET',
        title='东方财富大盘资金流',
        doc_file='东方财富大盘资金流.md',
        original_api='get_eastmoney_dapan_flow',
        params=('trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_futures_position': Endpoint(
        name='eastmoney_futures_position',
        path='api/v1/market/data/eastmoney-futures-position',
        method='GET',
        title='东方财富期货持仓',
        doc_file='东方财富期货持仓.md',
        original_api='get_eastmoney_futures_position',
        params=('exchange', 'variety_code', 'contract_code', 'trade_date', 'start_date', 'end_date', 'member_name_abbr', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_hk_index_daily_kline': Endpoint(
        name='eastmoney_hk_index_daily_kline',
        path='api/v1/market/data/eastmoney-hk-index-daily-kline',
        method='GET',
        title='东方财富港股指数日K',
        doc_file='东方财富港股指数日K.md',
        original_api='get_eastmoney_hk_index_daily_kline',
        params=('index_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_market_valuation': Endpoint(
        name='eastmoney_market_valuation',
        path='api/v1/market/data/eastmoney-market-valuation',
        method='GET',
        title='东方财富市场估值',
        doc_file='东方财富市场估值.md',
        original_api='get_eastmoney_market_valuation',
        params=('market_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_rank': Endpoint(
        name='eastmoney_rank',
        path='api/v1/market/data/eastmoney-rank',
        method='GET',
        title='东方财富股票排名',
        doc_file='东方财富股票排名.md',
        original_api='eastmoney_rank',
        params=('rank_group', 'market', 'trade_date'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_sector_flow': Endpoint(
        name='eastmoney_sector_flow',
        path='api/v1/market/data/eastmoney-sector-flow',
        method='GET',
        title='东方财富板块资金流',
        doc_file='东方财富板块资金流.md',
        original_api='get_eastmoney_sector_flow',
        params=('sector_code', 'sector_type', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_stock_flow': Endpoint(
        name='eastmoney_stock_flow',
        path='api/v1/market/data/eastmoney-stock-flow',
        method='GET',
        title='东方财富个股资金流',
        doc_file='东方财富个股资金流.md',
        original_api='get_eastmoney_stock_flow',
        params=('symbol', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_stock_valuation': Endpoint(
        name='eastmoney_stock_valuation',
        path='api/v1/market/data/eastmoney-stock-valuation',
        method='GET',
        title='东方财富个股估值',
        doc_file='东方财富个股估值.md',
        original_api='get_eastmoney_stock_valuation',
        params=('symbol', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_us_stock_daily_kline': Endpoint(
        name='eastmoney_us_stock_daily_kline',
        path='api/v1/market/data/eastmoney-us-stock-daily-ohlc',
        method='GET',
        title='东方财富美股日OHLC',
        doc_file='东方财富美股日OHLC.md',
        original_api='eastmoney_us_stock_daily_kline',
        params=('stock_code', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_us_stock_latest_kline': Endpoint(
        name='eastmoney_us_stock_latest_kline',
        path='api/v1/market/data/eastmoney-us-stock-latest-ohlc',
        method='GET',
        title='东方财富美股最新OHLC',
        doc_file='东方财富美股最新OHLC.md',
        original_api='eastmoney_us_stock_latest_kline',
        params=('stock_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_us_stock_list': Endpoint(
        name='eastmoney_us_stock_list',
        path='api/v1/market/data/eastmoney-us-stock-list',
        method='GET',
        title='东方财富美股列表',
        doc_file='东方财富美股列表.md',
        original_api='eastmoney_us_stock_list',
        params=('refresh', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'etf_adjust_factor': Endpoint(
        name='etf_adjust_factor',
        path='api/v1/market/data/etf-adjust-factor',
        method='GET',
        title='ETF复权因子',
        doc_file='ETF复权因子.md',
        original_api='etf_adjust_factor',
        params=('symbol', 'trade_date', 'start_date', 'end_date', 'offset', 'limit'),
        path_params=(),
        max_page_size=200,
    ),
    'etf_components': Endpoint(
        name='etf_components',
        path='api/v1/market/data/etf-component',
        method='GET',
        title='ETF成份股',
        doc_file='ETF成份股.md',
        original_api='get_etf_components_handler',
        params=('symbol',),
        path_params=(),
        max_page_size=200,
    ),
    'etf_components_all': Endpoint(
        name='etf_components_all',
        path='api/v1/market/data/etf-components-all',
        method='GET',
        title='ETF成份列表',
        doc_file='ETF成份列表.md',
        original_api='etf_components_all',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'etf_description_all': Endpoint(
        name='etf_description_all',
        path='api/v1/market/data/etf-description-all',
        method='GET',
        title='ETF基础信息',
        doc_file='ETF基础信息.md',
        original_api='etf_description_all',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'etf_fund_export': Endpoint(
        name='etf_fund_export',
        path='api/v1/market/data/etf/zhitou-etf',
        method='GET',
        title='指数ETF基金导出',
        doc_file='指数ETF基金导出.md',
        original_api='etf_fund_export',
        params=('request_id', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'etf_pcf_list': Endpoint(
        name='etf_pcf_list',
        path='api/v1/market/data/etf-pcf/etf-pcfs',
        method='GET',
        title='ETF-PCF清单列表',
        doc_file='ETF-PCF清单列表.md',
        original_api='etf_pcf_list_handler',
        params=('date', 'page', 'page_size'),
        path_params=(),
        max_page_size=100,
    ),
    'etf_pre': Endpoint(
        name='etf_pre',
        path='api/v1/market/data/etf-pre-data',
        method='GET',
        title='ETF盘前数据',
        doc_file='ETF盘前数据.md',
        original_api='get_etf_pre',
        params=('date',),
        path_params=(),
        max_page_size=200,
    ),
    'etf_pre_single': Endpoint(
        name='etf_pre_single',
        path='api/v1/market/data/etf-pre-single',
        method='GET',
        title='单只ETF盘前数据',
        doc_file='单只ETF盘前数据.md',
        original_api='get_etf_pre_single_handler',
        params=('symbol', 'date'),
        path_params=(),
        max_page_size=200,
    ),
    'fund_basicinfo': Endpoint(
        name='fund_basicinfo',
        path='api/v1/market/data/fund/fund-basicinfo',
        method='GET',
        title='基金基础信息',
        doc_file='基金基础信息.md',
        original_api='get_fund_basicinfo',
        params=('institution_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'fund_cal_return': Endpoint(
        name='fund_cal_return',
        path='api/v1/market/data/fund/fund-cal-return',
        method='GET',
        title='基金收益',
        doc_file='基金收益.md',
        original_api='get_fund_cal_return',
        params=('institution_code', 'cal-type'),
        path_params=(),
        max_page_size=200,
    ),
    'fund_nav': Endpoint(
        name='fund_nav',
        path='api/v1/market/data/fund/fund-nav',
        method='GET',
        title='基金净值',
        doc_file='基金净值.md',
        original_api='get_fund_nav',
        params=('institution_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'fund_overview': Endpoint(
        name='fund_overview',
        path='api/v1/market/data/fund/fund-overview',
        method='GET',
        title='基金总览',
        doc_file='基金总览.md',
        original_api='get_fund_overview',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'fund_support_symbols': Endpoint(
        name='fund_support_symbols',
        path='api/v1/market/data/fund/fund-support-symbols',
        method='GET',
        title='基金支持标的',
        doc_file='基金支持标的.md',
        original_api='get_fund_support_symbols',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'futures_contract_kline': Endpoint(
        name='futures_contract_kline',
        path='api/v1/market/data/futures/kline',
        method='GET',
        title='期货合约K线',
        doc_file='期货合约K线.md',
        original_api='futures_contract_kline',
        params=('symbol', 'interval', 'start', 'end', 'limit'),
        path_params=(),
        max_page_size=200,
    ),
    'global_index_daily_kline': Endpoint(
        name='global_index_daily_kline',
        path='api/v1/market/data/global-index/daily-kline',
        method='GET',
        title='全球指数日K线',
        doc_file='全球指数日K线.md',
        original_api='global_index_daily_kline',
        params=('secid', 'start_date', 'end_date'),
        path_params=(),
        max_page_size=200,
    ),
    'goodwill_industry': Endpoint(
        name='goodwill_industry',
        path='api/v1/market/data/goodwill/industry',
        method='GET',
        title='商誉行业',
        doc_file='商誉行业.md',
        original_api='goodwill_industry',
        params=('date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'goodwill_market_overview': Endpoint(
        name='goodwill_market_overview',
        path='api/v1/market/data/goodwill/market-overview',
        method='GET',
        title='商誉市场总览',
        doc_file='商誉市场总览.md',
        original_api='goodwill_market_overview',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'goodwill_predict': Endpoint(
        name='goodwill_predict',
        path='api/v1/market/data/goodwill/predict',
        method='GET',
        title='商誉预测',
        doc_file='商誉预测.md',
        original_api='goodwill_predict',
        params=('date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'goodwill_stock_detail': Endpoint(
        name='goodwill_stock_detail',
        path='api/v1/market/data/goodwill/stock-detail',
        method='GET',
        title='商誉个股明细',
        doc_file='商誉个股明细.md',
        original_api='goodwill_stock_detail',
        params=('date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'goodwill_stock_impairment': Endpoint(
        name='goodwill_stock_impairment',
        path='api/v1/market/data/goodwill/stock-impairment',
        method='GET',
        title='商誉减值',
        doc_file='商誉减值.md',
        original_api='goodwill_stock_impairment',
        params=('date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'hk_balance_bank': Endpoint(
        name='hk_balance_bank',
        path='api/v1/market/data/hk/hk-balance-bank',
        method='GET',
        title='港股资产负债表',
        doc_file='港股资产负债表.md',
        original_api='hk_balance_bank',
        params=('trade_code', 'year', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'hk_balance_gene': Endpoint(
        name='hk_balance_gene',
        path='api/v1/market/data/hk/hk-balance-gene',
        method='GET',
        title='港股资产负债表',
        doc_file='港股资产负债表.md',
        original_api='hk_balance_gene',
        params=('trade_code', 'year', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'hk_balance_insur': Endpoint(
        name='hk_balance_insur',
        path='api/v1/market/data/hk/hk-balance-insur',
        method='GET',
        title='港股资产负债表',
        doc_file='港股资产负债表.md',
        original_api='hk_balance_insur',
        params=('trade_code', 'year', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'hk_basinfo_get': Endpoint(
        name='hk_basinfo_get',
        path='api/v1/market/data/hk/hk-view',
        method='GET',
        title='港股个股信息',
        doc_file='港股个股信息.md',
        original_api='get_hk_basinfo_get',
        params=('hk_code',),
        path_params=(),
        max_page_size=200,
    ),
    'hk_basinfo_post': Endpoint(
        name='hk_basinfo_post',
        path='api/v1/market/data/hk/hk-view',
        method='GET',
        title='港股个股信息',
        doc_file='港股个股信息.md',
        original_api='get_hk_basinfo_post',
        params=('hk_code',),
        path_params=(),
        max_page_size=200,
    ),
    'hk_candlesticks': Endpoint(
        name='hk_candlesticks',
        path='api/v1/market/data/hk/hk-candlesticks',
        method='GET',
        title='港股K线',
        doc_file='港股K线.md',
        original_api='get_hk_candlesticks',
        params=('trade_code', 'interval_unit', 'until_date', 'since_date', 'interval_value', 'limit', 'adjust_kind'),
        path_params=(),
        max_page_size=200,
    ),
    'hk_cashflow': Endpoint(
        name='hk_cashflow',
        path='api/v1/market/data/hk/hk-cashflow',
        method='GET',
        title='港股现金流量表',
        doc_file='港股现金流量表.md',
        original_api='hk_cashflow',
        params=('stock_code', 'year', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'hk_income_bank': Endpoint(
        name='hk_income_bank',
        path='api/v1/market/data/hk/hk-income-bank',
        method='GET',
        title='港股利润表',
        doc_file='港股利润表.md',
        original_api='hk_income_bank',
        params=('trade_code', 'year', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'hk_income_gene': Endpoint(
        name='hk_income_gene',
        path='api/v1/market/data/hk/hk-income-gene',
        method='GET',
        title='港股利润表',
        doc_file='港股利润表.md',
        original_api='hk_income_gene',
        params=('trade_code', 'year', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'hk_income_insur': Endpoint(
        name='hk_income_insur',
        path='api/v1/market/data/hk/hk-income-insur',
        method='GET',
        title='港股利润表',
        doc_file='港股利润表.md',
        original_api='hk_income_insur',
        params=('trade_code', 'year', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'hk_sh_stock_connect_members': Endpoint(
        name='hk_sh_stock_connect_members',
        path='api/v1/market/data/hk-sh-stock-connect-members',
        method='GET',
        title='沪港通成份',
        doc_file='沪港通成份.md',
        original_api='hk_sh_stock_connect_members',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'hk_sz_stock_connect_members': Endpoint(
        name='hk_sz_stock_connect_members',
        path='api/v1/market/data/hk-sz-stock-connect-members',
        method='GET',
        title='深港通成份',
        doc_file='深港通成份.md',
        original_api='hk_sz_stock_connect_members',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'hk_valuatnanalyd': Endpoint(
        name='hk_valuatnanalyd',
        path='api/v1/market/data/hk/hk-valuatnanalyd',
        method='GET',
        title='港股估值分析',
        doc_file='港股估值分析.md',
        original_api='get_hk_valuatnanalyd',
        params=('trade_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'income': Endpoint(
        name='income',
        path='api/v1/market/data/finance/income',
        method='GET',
        title='A股利润表',
        doc_file='A股利润表.md',
        original_api='income',
        params=('stock_code', 'year', 'report_type', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'index_description_all': Endpoint(
        name='index_description_all',
        path='api/v1/market/data/index-description-all',
        method='GET',
        title='指数基础信息',
        doc_file='指数基础信息.md',
        original_api='index_description_all',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'index_description_list': Endpoint(
        name='index_description_list',
        path='api/v1/market/data/index/index_description',
        method='GET',
        title='中证指数描述列表',
        doc_file='中证指数描述列表.md',
        original_api='index_description_list_handler',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=100,
    ),
    'index_weight_list': Endpoint(
        name='index_weight_list',
        path='api/v1/market/data/index/index_weight',
        method='GET',
        title='指数权重列表',
        doc_file='指数权重列表.md',
        original_api='index_weight_list_handler',
        params=('index_code', 'date', 'page', 'page_size'),
        path_params=(),
        max_page_size=100,
    ),
    'index_weight_summary': Endpoint(
        name='index_weight_summary',
        path='api/v1/market/data/index/index_weight_summary',
        method='GET',
        title='指数权重汇总',
        doc_file='指数权重汇总.md',
        original_api='index_weight_summary_handler',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=100,
    ),
    'limit_down_pool': Endpoint(
        name='limit_down_pool',
        path='api/v1/market/data/limit-down-pool',
        method='GET',
        title='跌停池',
        doc_file='跌停池.md',
        original_api='limit_down_pool',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'limit_event_timeline_3s': Endpoint(
        name='limit_event_timeline_3s',
        path='api/v1/market/data/limit-event-timeline-3s',
        method='GET',
        title='涨跌停事件时间线',
        doc_file='涨跌停事件时间线.md',
        original_api='limit_event_timeline_3s',
        params=('symbol',),
        path_params=(),
        max_page_size=200,
    ),
    'limit_up_break_pool': Endpoint(
        name='limit_up_break_pool',
        path='api/v1/market/data/limit-up-break-pool',
        method='GET',
        title='炸板池',
        doc_file='炸板池.md',
        original_api='limit_up_break_pool',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'limit_up_pool': Endpoint(
        name='limit_up_pool',
        path='api/v1/market/data/limit-up-pool',
        method='GET',
        title='涨停池',
        doc_file='涨停池.md',
        original_api='limit_up_pool',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'limit_up_pool_yesterday': Endpoint(
        name='limit_up_pool_yesterday',
        path='api/v1/market/data/limit-up-pool-yesterday',
        method='GET',
        title='昨日涨停池',
        doc_file='昨日涨停池.md',
        original_api='limit_up_pool_yesterday',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'lpr_monthly': Endpoint(
        name='lpr_monthly',
        path='api/v1/market/data/economic/china-lpr',
        method='GET',
        title='LPR',
        doc_file='LPR.md',
        original_api='lpr_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'major_contract': Endpoint(
        name='major_contract',
        path='api/v1/market/data/corporate/contract',
        method='GET',
        title='重大合同',
        doc_file='重大合同.md',
        original_api='major_contract',
        params=('start_date', 'end_date'),
        path_params=(),
        max_page_size=3,
    ),
    'major_contract_by_symbol': Endpoint(
        name='major_contract_by_symbol',
        path='api/v1/market/data/corporate/contract/by-symbol',
        method='GET',
        title='重大合同按标的',
        doc_file='重大合同按标的.md',
        original_api='major_contract_by_symbol',
        params=('symbol', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'major_contract_summary': Endpoint(
        name='major_contract_summary',
        path='api/v1/market/data/corporate/contract/summary',
        method='GET',
        title='重大合同汇总',
        doc_file='重大合同汇总.md',
        original_api='major_contract_summary',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'margin_trading_details': Endpoint(
        name='margin_trading_details',
        path='api/v1/market/data/margin-trading-details',
        method='GET',
        title='融资融券明细',
        doc_file='融资融券明细.md',
        original_api='margin_trading_details',
        params=('date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'margin_trading_details_paginated': Endpoint(
        name='margin_trading_details_paginated',
        path='api/v1/market/data/margin-trading-details',
        method='GET',
        title='融资融券明细分页',
        doc_file='融资融券明细分页.md',
        original_api='margin_trading_details_paginated',
        params=('date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'market_cap_hk': Endpoint(
        name='market_cap_hk',
        path='api/v1/market/data/hk/market-cap-hk',
        method='GET',
        title='港股市值',
        doc_file='港股市值.md',
        original_api='get_market_cap_hk',
        params=('trade_code',),
        path_params=(),
        max_page_size=200,
    ),
    'northbound': Endpoint(
        name='northbound',
        path='api/v1/market/data/northbound',
        method='GET',
        title='北向资金交易',
        doc_file='北向资金交易.md',
        original_api='northbound',
        params=('date',),
        path_params=(),
        max_page_size=200,
    ),
    'nth_trade_date': Endpoint(
        name='nth_trade_date',
        path='api/v1/market/data/time/get-nth-trade-date',
        method='GET',
        title='第N个交易日',
        doc_file='第N个交易日.md',
        original_api='get_nth_trade_date',
        params=('n',),
        path_params=(),
        max_page_size=200,
    ),
    'performance_forecasts_paginated': Endpoint(
        name='performance_forecasts_paginated',
        path='api/v1/market/data/finance/stock-performance-forecast',
        method='GET',
        title='业绩预告',
        doc_file='业绩预告.md',
        original_api='performance_forecasts_paginated',
        params=('stock_code', 'year', 'report_type', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'price_change': Endpoint(
        name='price_change',
        path='api/v1/market/data/price/get-price-change',
        method='GET',
        title='价格变动',
        doc_file='价格变动.md',
        original_api='get_price_change',
        params=('stock_code', 'base_date', 'n', 'direction'),
        path_params=(),
        max_page_size=200,
    ),
    'reserve_ratio_monthly': Endpoint(
        name='reserve_ratio_monthly',
        path='api/v1/market/data/economic/china-reserve-ratio',
        method='GET',
        title='存款准备金率',
        doc_file='存款准备金率.md',
        original_api='reserve_ratio_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'risk_warning_stock_quotes': Endpoint(
        name='risk_warning_stock_quotes',
        path='api/v1/market/data/risk-warning-stocks/quotes',
        method='GET',
        title='风险警示股行情',
        doc_file='风险警示股行情.md',
        original_api='risk_warning_stock_quotes',
        params=('date',),
        path_params=(),
        max_page_size=200,
    ),
    'risk_warning_stocks': Endpoint(
        name='risk_warning_stocks',
        path='api/v1/market/data/risk-warning-stocks',
        method='GET',
        title='风险警示股',
        doc_file='风险警示股.md',
        original_api='risk_warning_stocks',
        params=('date',),
        path_params=(),
        max_page_size=200,
    ),
    'search': Endpoint(
        name='search',
        path='api/v1/market/security/search',
        method='GET',
        title='标的搜索',
        doc_file='标的搜索.md',
        original_api='search',
        params=('query', 'limit'),
        path_params=(),
        max_page_size=200,
    ),
    'semantic_search_news': Endpoint(
        name='semantic_search_news',
        path='api/v1/market/data/semantic-search-news',
        method='GET',
        title='新闻语义搜索',
        doc_file='新闻语义搜索.md',
        original_api='semantic_search_news_handler',
        params=('query', 'limit', 'year', 'start_time', 'end_time'),
        path_params=(),
        max_page_size=200,
    ),
    'sh_hk_stock_connect_members': Endpoint(
        name='sh_hk_stock_connect_members',
        path='api/v1/market/data/sh-hk-stock-connect-members',
        method='GET',
        title='沪股通成份',
        doc_file='沪股通成份.md',
        original_api='sh_hk_stock_connect_members',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'shareholders_meeting': Endpoint(
        name='shareholders_meeting',
        path='api/v1/market/data/corporate/meeting',
        method='GET',
        title='股东大会',
        doc_file='股东大会.md',
        original_api='shareholders_meeting',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'southbound': Endpoint(
        name='southbound',
        path='api/v1/market/data/southbound',
        method='GET',
        title='南向资金交易',
        doc_file='南向资金交易.md',
        original_api='southbound',
        params=('date',),
        path_params=(),
        max_page_size=200,
    ),
    'stk_ah_comparison': Endpoint(
        name='stk_ah_comparison',
        path='api/v1/market/data/hk/stk-ah-comparison',
        method='GET',
        title='AH股对比',
        doc_file='AH股对比.md',
        original_api='get_stk_ah_comparison',
        params=('hk_code', 'ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=1000,
    ),
    'stk_limit': Endpoint(
        name='stk_limit',
        path='api/v1/market/data/stk-limit',
        method='GET',
        title='涨跌停价',
        doc_file='涨跌停价.md',
        original_api='stk_limit',
        params=('instrument_type', 'symbol', 'symbol_id', 'market_id', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'stk_premarket': Endpoint(
        name='stk_premarket',
        path='api/v1/market/data/stk-premarket',
        method='GET',
        title='盘前数据',
        doc_file='盘前数据.md',
        original_api='stk_premarket',
        params=('ts_code', 'trade_date', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'stock_adjust_factor': Endpoint(
        name='stock_adjust_factor',
        path='api/v1/market/data/stock-adjust-factor',
        method='GET',
        title='股票复权因子',
        doc_file='股票复权因子.md',
        original_api='stock_adjust_factor',
        params=('symbol', 'trade_date', 'start_date', 'end_date', 'offset', 'limit'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_announcements': Endpoint(
        name='stock_announcements',
        path='api/v1/market/data/announcements/stock-announcements',
        method='GET',
        title='公告列表',
        doc_file='公告列表.md',
        original_api='stock_announcements',
        params=('stock_code', 'start_date', 'end_date', 'type', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_candlesticks': Endpoint(
        name='stock_candlesticks',
        path='api/v1/market/data/stock-candlesticks',
        method='POST',
        title='股票K线',
        doc_file='股票K线.md',
        original_api='stock_candlesticks',
        params=('symbol', 'interval_unit', 'interval_value', 'adjust_kind', 'since_ts_millis', 'until_ts_millis', 'limit'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_candlesticks_batch': Endpoint(
        name='stock_candlesticks_batch',
        path='api/v1/market/data/stock-candlesticks/batch',
        method='POST',
        title='批量股票K线',
        doc_file='批量股票K线.md',
        original_api='stock_candlesticks_batch',
        params=('symbols', 'interval_unit', 'interval_value', 'adjust_kind', 'since_ts_millis', 'until_ts_millis', 'limit'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_capital_flows_paginated': Endpoint(
        name='stock_capital_flows_paginated',
        path='api/v1/market/data/stock-capital-flows',
        method='GET',
        title='股票资金流向',
        doc_file='股票资金流向.md',
        original_api='stock_capital_flows_paginated',
        params=('date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_comment_desire_em': Endpoint(
        name='stock_comment_desire_em',
        path='api/v1/market/data/stock-comment/desire',
        method='GET',
        title='千股千评意愿度',
        doc_file='千股千评意愿度.md',
        original_api='stock_comment_desire_em',
        params=('symbol',),
        path_params=(),
        max_page_size=200,
    ),
    'stock_comment_em': Endpoint(
        name='stock_comment_em',
        path='api/v1/market/data/stock-comment/index',
        method='GET',
        title='千股千评',
        doc_file='千股千评.md',
        original_api='stock_comment_em',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_comment_focus_em': Endpoint(
        name='stock_comment_focus_em',
        path='api/v1/market/data/stock-comment/focus',
        method='GET',
        title='千股千评关注度',
        doc_file='千股千评关注度.md',
        original_api='stock_comment_focus_em',
        params=('symbol',),
        path_params=(),
        max_page_size=200,
    ),
    'stock_comment_org_participate_em': Endpoint(
        name='stock_comment_org_participate_em',
        path='api/v1/market/data/stock-comment/org-participate',
        method='GET',
        title='机构参与度',
        doc_file='机构参与度.md',
        original_api='stock_comment_org_participate_em',
        params=('symbol',),
        path_params=(),
        max_page_size=200,
    ),
    'stock_comment_score_em': Endpoint(
        name='stock_comment_score_em',
        path='api/v1/market/data/stock-comment/score',
        method='GET',
        title='千股千评评分',
        doc_file='千股千评评分.md',
        original_api='stock_comment_score_em',
        params=('symbol',),
        path_params=(),
        max_page_size=200,
    ),
    'stock_dividends_paginated': Endpoint(
        name='stock_dividends_paginated',
        path='api/v1/market/data/dividends',
        method='GET',
        title='股票分红记录分页',
        doc_file='股票分红记录分页.md',
        original_api='stock_dividends_paginated',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_filter': Endpoint(
        name='stock_filter',
        path='api/v1/market/data/stock-list/filter',
        method='GET',
        title='股票筛选',
        doc_file='股票筛选.md',
        original_api='stock_filter',
        params=('board', 'listing_date_since', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_float_holders': Endpoint(
        name='stock_float_holders',
        path='api/v1/market/data/holder/stock-holder-ften',
        method='GET',
        title='十大流通股东',
        doc_file='十大流通股东.md',
        original_api='stock_float_holders',
        params=('stock_code', 'is_last', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_ggcg_em': Endpoint(
        name='stock_ggcg_em',
        path='api/v1/market/data/holder/stock-ggcg-em',
        method='GET',
        title='东方财富股东增减持',
        doc_file='东方财富股东增减持.md',
        original_api='stock_ggcg_em_handler',
        params=('symbol', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_ggmx': Endpoint(
        name='stock_ggmx',
        path='api/v1/market/data/holder/stock-ggmx',
        method='GET',
        title='董监高持股变动',
        doc_file='董监高持股变动.md',
        original_api='stock_ggmx_handler',
        params=('stock_code', 'change_direction', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_ggmx_buy_ranking': Endpoint(
        name='stock_ggmx_buy_ranking',
        path='api/v1/market/data/holder/stock-ggmx-buy-ranking',
        method='GET',
        title='董监高增持排名',
        doc_file='董监高增持排名.md',
        original_api='stock_ggmx_buy_ranking_handler',
        params=('time_range', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_ggmx_sell_ranking': Endpoint(
        name='stock_ggmx_sell_ranking',
        path='api/v1/market/data/holder/stock-ggmx-sell-ranking',
        method='GET',
        title='董监高减持排名',
        doc_file='董监高减持排名.md',
        original_api='stock_ggmx_sell_ranking_handler',
        params=('time_range', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_holders': Endpoint(
        name='stock_holders',
        path='api/v1/market/data/holder/stock-holder-ten',
        method='GET',
        title='十大股东',
        doc_file='十大股东.md',
        original_api='stock_holders',
        params=('stock_code', 'is_last', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_holders_number': Endpoint(
        name='stock_holders_number',
        path='api/v1/market/data/holder/stock-holder-nums',
        method='GET',
        title='股东人数',
        doc_file='股东人数.md',
        original_api='stock_holders_number',
        params=('stock_code', 'is_last', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_institution_holdings': Endpoint(
        name='stock_institution_holdings',
        path='api/v1/market/data/share/stock-institution-holdings',
        method='GET',
        title='机构持股',
        doc_file='机构持股.md',
        original_api='get_stock_institution_holdings',
        params=('year', 'report_type', 'inst_type', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_institution_holdings_detail': Endpoint(
        name='stock_institution_holdings_detail',
        path='api/v1/market/data/share/stock-institution-holdings-detail',
        method='GET',
        title='机构持股明细',
        doc_file='机构持股明细.md',
        original_api='get_stock_institution_holdings_detail',
        params=('stock_code', 'year', 'report_type', 'inst_type', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_institution_share_holdings': Endpoint(
        name='stock_institution_share_holdings',
        path='api/v1/market/data/institution/institution-share-holdings',
        method='GET',
        title='机构股本持股',
        doc_file='机构股本持股.md',
        original_api='get_stock_institution_share_holdings',
        params=('institution_id', 'year', 'report_type', 'invest_type'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_intraday': Endpoint(
        name='stock_intraday',
        path='api/v1/market/security/{symbol}/intraday',
        method='GET',
        title='股票日内分时',
        doc_file='股票日内分时.md',
        original_api='stock_intraday',
        params=('symbol',),
        path_params=('symbol',),
        max_page_size=200,
    ),
    'stock_intraday_auction_volume': Endpoint(
        name='stock_intraday_auction_volume',
        path='api/v1/market/data/intraday-auction-volume',
        method='GET',
        title='集合竞价成交量',
        doc_file='集合竞价成交量.md',
        original_api='stock_intraday_auction_volume',
        params=('trade_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_intraday_auction_volume_symbol': Endpoint(
        name='stock_intraday_auction_volume_symbol',
        path='api/v1/market/data/intraday-auction-volume/symbol',
        method='GET',
        title='单标的集合竞价成交量',
        doc_file='单标的集合竞价成交量.md',
        original_api='stock_intraday_auction_volume_symbol',
        params=('symbol', 'trade_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_ipos': Endpoint(
        name='stock_ipos',
        path='api/v1/market/data/stock-ipos',
        method='GET',
        title='股票IPO',
        doc_file='股票IPO.md',
        original_api='stock_ipos',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_ipos_paginated': Endpoint(
        name='stock_ipos_paginated',
        path='api/v1/market/data/stock-ipos',
        method='GET',
        title='股票IPO分页',
        doc_file='股票IPO分页.md',
        original_api='stock_ipos_paginated',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_list': Endpoint(
        name='stock_list',
        path='api/v1/market/data/stock-list',
        method='GET',
        title='股票列表',
        doc_file='股票列表.md',
        original_api='get_stock_list',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'stock_market': Endpoint(
        name='stock_market',
        path='api/v1/market/data/daec/market/snapshot',
        method='GET',
        title='股票市场行情',
        doc_file='股票市场行情.md',
        original_api='stock_market',
        params=('scope',),
        path_params=(),
        max_page_size=200,
    ),
    'stock_market_distribution_intraday': Endpoint(
        name='stock_market_distribution_intraday',
        path='api/v1/market/data/daec/market/distribution-history',
        method='GET',
        title='市场涨跌分布分时',
        doc_file='市场涨跌分布分时.md',
        original_api='stock_market_distribution_intraday',
        params=('scope',),
        path_params=(),
        max_page_size=200,
    ),
    'stock_pledge_detail': Endpoint(
        name='stock_pledge_detail',
        path='api/v1/market/data/pledge/pledge-detail',
        method='GET',
        title='股权质押明细',
        doc_file='股权质押明细.md',
        original_api='stock_pledge_detail',
        params=('stock_code', 'is_last', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_pledge_summary': Endpoint(
        name='stock_pledge_summary',
        path='api/v1/market/data/pledge/pledge-summary',
        method='GET',
        title='股权质押汇总',
        doc_file='股权质押汇总.md',
        original_api='stock_pledge_summary',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_prev_close': Endpoint(
        name='stock_prev_close',
        path='api/v1/market/data/daec/history/prev-closes',
        method='GET',
        title='股票前收盘价',
        doc_file='股票前收盘价.md',
        original_api='stock_prev_close',
        params=('symbol', 'since', 'until'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_rating_top5': Endpoint(
        name='stock_rating_top5',
        path='api/v1/market/data/feitu/stock-rating-top5',
        method='GET',
        title='飞兔股票评级Top5',
        doc_file='飞兔股票评级Top5.md',
        original_api='stock_rating_top5',
        params=('date', 'variant', 'type'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_related': Endpoint(
        name='stock_related',
        path='api/v1/market/security/{symbol}/related',
        method='GET',
        title='相关股票',
        doc_file='相关股票.md',
        original_api='stock_related',
        params=('symbol', 'limit'),
        path_params=('symbol',),
        max_page_size=200,
    ),
    'stock_reports': Endpoint(
        name='stock_reports',
        path='api/v1/market/data/report/stock-reports',
        method='GET',
        title='研报列表',
        doc_file='研报列表.md',
        original_api='stock_reports',
        params=('stock_code', 'start_date', 'end_date', 'type', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_share': Endpoint(
        name='stock_share',
        path='api/v1/market/data/share/get-stock-share',
        method='GET',
        title='股本',
        doc_file='股本.md',
        original_api='get_stock_share_handler',
        params=('stock_code', 'date'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_share_chg': Endpoint(
        name='stock_share_chg',
        path='api/v1/market/data/holder/stock-share-chg',
        method='GET',
        title='股东增减持',
        doc_file='股东增减持.md',
        original_api='stock_share_chg',
        params=('stock_code', 'is_last', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_signal_latest_snapshot': Endpoint(
        name='stock_signal_latest_snapshot',
        path='api/v1/market/data/stock-signal-latest-snapshot',
        method='GET',
        title='信号最新快照',
        doc_file='信号最新快照.md',
        original_api='stock_signal_latest_snapshot',
        params=('signal_type', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_trade': Endpoint(
        name='stock_trade',
        path='api/v1/market/data/daec/history/trades',
        method='GET',
        title='股票分时成交',
        doc_file='股票分时成交.md',
        original_api='stock_trade',
        params=('symbol',),
        path_params=(),
        max_page_size=200,
    ),
    'stock_unlock': Endpoint(
        name='stock_unlock',
        path='api/v1/market/data/unlock/stock-unlock',
        method='GET',
        title='限售解禁',
        doc_file='限售解禁.md',
        original_api='stock_unlock_handler',
        params=('stock_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_unlock_by_date': Endpoint(
        name='stock_unlock_by_date',
        path='api/v1/market/data/unlock/stock-unlock-by-date',
        method='GET',
        title='限售解禁按日期',
        doc_file='限售解禁按日期.md',
        original_api='stock_unlock_by_date_handler',
        params=('start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'suspension_list': Endpoint(
        name='suspension_list',
        path='api/v1/market/data/suspension-list',
        method='GET',
        title='停牌列表',
        doc_file='停牌列表.md',
        original_api='suspension_list',
        params=('trade_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'sw_industry_constituent_history': Endpoint(
        name='sw_industry_constituent_history',
        path='api/v1/market/data/sw-industry/constituent-history',
        method='GET',
        title='申万行业成份股历史',
        doc_file='申万行业成份股历史.md',
        original_api='sw_industry_constituent_history',
        params=('industry_code',),
        path_params=(),
        max_page_size=200,
    ),
    'sw_industry_daily_metrics': Endpoint(
        name='sw_industry_daily_metrics',
        path='api/v1/market/data/sw-industry/daily-metrics',
        method='GET',
        title='申万行业日度指标',
        doc_file='申万行业日度指标.md',
        original_api='sw_industry_daily_metrics',
        params=('level', 'start_date', 'end_date', 'industry_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'sw_industry_overview': Endpoint(
        name='sw_industry_overview',
        path='api/v1/market/data/sw-industry/overview',
        method='GET',
        title='申万行业总览',
        doc_file='申万行业总览.md',
        original_api='sw_industry_overview',
        params=('date', 'level', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'sz_hk_stock_connect_members': Endpoint(
        name='sz_hk_stock_connect_members',
        path='api/v1/market/data/sz-hk-stock-connect-members',
        method='GET',
        title='深股通成份',
        doc_file='深股通成份.md',
        original_api='sz_hk_stock_connect_members',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'tax_revenue_monthly': Endpoint(
        name='tax_revenue_monthly',
        path='api/v1/market/data/economic/china-tax-revenue',
        method='GET',
        title='税收',
        doc_file='税收.md',
        original_api='tax_revenue_monthly',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'ths_all_board_kline': Endpoint(
        name='ths_all_board_kline',
        path='api/v1/market/data/ths-all-board-kline',
        method='GET',
        title='同花顺全板块K线',
        doc_file='同花顺全板块K线.md',
        original_api='ths_all_board_kline',
        params=('start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'ths_board_kline': Endpoint(
        name='ths_board_kline',
        path='api/v1/market/data/ths-board-kline',
        method='GET',
        title='同花顺板块K线',
        doc_file='同花顺板块K线.md',
        original_api='ths_board_kline',
        params=('board_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'ths_board_list': Endpoint(
        name='ths_board_list',
        path='api/v1/market/data/ths-board-list',
        method='GET',
        title='同花顺板块列表',
        doc_file='同花顺板块列表.md',
        original_api='ths_board_list',
        params=(),
        path_params=(),
        max_page_size=200,
    ),
    'type_reports': Endpoint(
        name='type_reports',
        path='api/v1/market/data/report/type-reports',
        method='GET',
        title='研报分类',
        doc_file='研报分类.md',
        original_api='type_reports',
        params=('rept_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'us_balance': Endpoint(
        name='us_balance',
        path='api/v1/market/data/us/us-balance',
        method='GET',
        title='美股资产负债表',
        doc_file='美股资产负债表.md',
        original_api='us_balance',
        params=('stock_code', 'period', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'us_basic': Endpoint(
        name='us_basic',
        path='api/v1/market/data/us/us-basic',
        method='GET',
        title='美股基础信息',
        doc_file='美股基础信息.md',
        original_api='us_basic',
        params=('stock_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'us_cashflow': Endpoint(
        name='us_cashflow',
        path='api/v1/market/data/us/us-cashflow',
        method='GET',
        title='美股现金流',
        doc_file='美股现金流.md',
        original_api='us_cashflow',
        params=('stock_code', 'period', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'us_economic': Endpoint(
        name='us_economic',
        path='api/v1/market/data/economic/us-economic',
        method='GET',
        title='美国经济指标',
        doc_file='美国经济指标.md',
        original_api='us_economic',
        params=('type',),
        path_params=(),
        max_page_size=200,
    ),
    'us_income': Endpoint(
        name='us_income',
        path='api/v1/market/data/us/us-income',
        method='GET',
        title='美股利润表',
        doc_file='美股利润表.md',
        original_api='us_income',
        params=('stock_code', 'period', 'report_type', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=500,
    ),
    'wallstreetcn_financial_calendar': Endpoint(
        name='wallstreetcn_financial_calendar',
        path='api/v1/market/data/finance/financial-calendar/wallstreetcn',
        method='GET',
        title='华尔街见闻财经日历',
        doc_file='华尔街见闻财经日历.md',
        original_api='wallstreetcn_financial_calendar',
        params=('start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'xueqiu_rank': Endpoint(
        name='xueqiu_rank',
        path='api/v1/market/data/xueqiu-rank',
        method='GET',
        title='雪球股票排名',
        doc_file='雪球股票排名.md',
        original_api='xueqiu_rank',
        params=('rank_group', 'period', 'trade_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=100,
    ),
    'yzxdr_detail': Endpoint(
        name='yzxdr_detail',
        path='api/v1/market/data/yzxdr-detail',
        method='GET',
        title='除权除息明细',
        doc_file='除权除息明细.md',
        original_api='get_yzxdr_detail',
        params=('year', 'quarter', 'stock_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_futures_strange': Endpoint(
        name='eastmoney_futures_strange',
        path='api/v1/market/data/eastmoney-futures-position',
        method='GET',
        title='东方财富期货持仓',
        doc_file='东方财富期货持仓.md',
        original_api='get_eastmoney_futures_position',
        params=('exchange', 'variety_code', 'contract_code', 'trade_date', 'start_date', 'end_date', 'member_name_abbr', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_us_stock_daily_ohlc': Endpoint(
        name='eastmoney_us_stock_daily_ohlc',
        path='api/v1/market/data/eastmoney-us-stock-daily-ohlc',
        method='GET',
        title='东方财富美股日OHLC',
        doc_file='东方财富美股日OHLC.md',
        original_api='eastmoney_us_stock_daily_kline',
        params=('stock_code', 'start_date', 'end_date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'eastmoney_us_stock_latest_ohlc': Endpoint(
        name='eastmoney_us_stock_latest_ohlc',
        path='api/v1/market/data/eastmoney-us-stock-latest-ohlc',
        method='GET',
        title='东方财富美股最新OHLC',
        doc_file='东方财富美股最新OHLC.md',
        original_api='eastmoney_us_stock_latest_kline',
        params=('stock_code', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'futures_kline': Endpoint(
        name='futures_kline',
        path='api/v1/market/data/futures/kline',
        method='GET',
        title='期货合约K线',
        doc_file='期货合约K线.md',
        original_api='futures_contract_kline',
        params=('symbol', 'interval', 'start', 'end', 'limit'),
        path_params=(),
        max_page_size=200,
    ),
    'pledge_summary': Endpoint(
        name='pledge_summary',
        path='api/v1/market/data/pledge/pledge-summary',
        method='GET',
        title='股权质押汇总',
        doc_file='股权质押汇总.md',
        original_api='stock_pledge_summary',
        params=('page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
    'stock_capital_flows': Endpoint(
        name='stock_capital_flows',
        path='api/v1/market/data/stock-capital-flows',
        method='GET',
        title='股票资金流向',
        doc_file='股票资金流向.md',
        original_api='stock_capital_flows_paginated',
        params=('date', 'page', 'page_size'),
        path_params=(),
        max_page_size=200,
    ),
}
